name: "Compare two openapi specifications for breaking changes"
description: "Compare two openapi specifications using the openapi-diff tool"
author: "API-Team"
inputs:
  path:
    description: "Path to the folder with the OAS files and output change log"
    required: false
    default: "oas"
  input_oas_old:
    description: "File name of the old OAS"
    required: false
    default: "openapi-old.yml"
  input_oas_new:
    description: "File name of the new OAS"
    required: false
    default: "openapi-new.yml"
  output_file:
    description: "Change log file name"
    required: false
    default: "change-log.md"

runs:
  using: "composite"
  steps:
    - name: Pull openapi-diff image
      shell: bash
      run: docker pull --quiet openapitools/openapi-diff

    - name: Run openapi-diff to compare two OASs
      shell: bash
      run: |
        set +e
        docker run --rm -t -v $(pwd)/${{ inputs.path }}:/data openapitools/openapi-diff:latest /data/${{ inputs.input_oas_old }} /data/${{ inputs.input_oas_new }} --fail-on-incompatible --markdown /data/${{ inputs.output_file }}
        exit_code=$?
        set -e
        if [[ $exit_code == 0 ]]; then
          echo "The comparison operation was successful. The new OAS version is compatible with the previous one."
          exit $?
        elif [[ $exit_code == 1 ]]; then
          echo "::warning:: The comparison operation was successful and the new OAS version is not compatible with the previous one."
          exit 1
        else
          echo "::error::Comparison operation failed, exit code is $exit_code"
          exit $exit_code
        fi
  