name: "Compare two openapi specifications"
description: "Compare two openapi specifications using the custom linter wrapper around spectral"
author: "API-Team"
inputs:
  registry_url:
    description: "URL of the docker registry, no trailing slashes. "
    default: ""
    required: false
  input_file_old:
    description: "path to the input file"
    required: false
    default: "openapi-old.yml"
  input_file_new:
    description: "path to the input file"
    required: false
    default: "openapi-new.yml"

runs:
  using: "composite"
  steps:
    - name: Pull openapi-diff image
      shell: bash
      run: docker pull --quiet openapitools/openapi-diff

    - name: Run openapi-diff to compare two files
      shell: bash
      run: ${{ github.action_path }}/compareOASs.sh ${{ inputs.input_file_old }} ${{ inputs.input_file_old }}