name: "Compare two openapi specifications"
description: "Compare two openapi specifications using the custom linter wrapper around spectral"
author: "API-Team"
inputs:
  path:
    description: "path to the folder with the OAS files and output change log"
    required: false
    default: "oas"
  input_oas_old:
    description: "path to the input file with old oas"
    required: false
    default: "openapi-old.yml"
  input_oas_new:
    description: "path to the input file with new oas"
    required: false
    default: "openapi-new.yml"
  output_file:
    description: "path to the output file with change log"
    required: false
    default: "change-log.md"

runs:
  using: "composite"
  steps:
    - name: Pull openapi-diff image
      shell: bash
      run: docker pull --quiet openapitools/openapi-diff

    - name: Run openapi-diff to compare two files
      shell: bash
      run: ${{ github.action_path }}/compareOASs.sh ${{ inputs.path }} ${{ inputs.input_oas_old }} ${{ inputs.input_oas_new }} ${{ inputs.output_file }}