name: "Compare two openapi specifications"
description: "Compare two openapi specifications using the custom linter wrapper around spectral"
author: "API-Team"
inputs:
  registry_url:
    description: "URL of the docker registry, no trailing slashes. "
    default: ""
    required: false
  image:
    description: "Name of the openapi-diff image"
    required: false
    default: "openapitools/openapi-diff"
  input_file_old:
    description: "path to the input file"
    required: false
    default: "openapi-old.yml"
  input_file_new:
    description: "path to the input file"
    required: false
    default: "openapi-new.yml"

runs:
  using: "composite"
  steps:
    - name: Pull openapi-diff image
      shell: bash
      run: docker pull --quiet ${{ inputs.image }}

    - name: Run openapi-diff to compare two files
      shell: bash
      run: |
        set +e
        docker run --rm -t -v $(pwd)/oas:/data ${{ inputs.image }}:latest /data/${{ inputs.input_file_old }} /data/${{ inputs.input_file_new }} --fail-on-incompatible
        exit_code=$?
        set -e
        if [[ $exit_code == 0 ]]; then
          echo "success"
        elif [[ $exit_code == 1 ]]; then
          echo "::warning::not compatible"
          exit 1
        else
          echo "::error::execution failed, exit_code=$exit_code"
          exit 2
        fi